artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "kelvinkelue/credit-card-fraud-prediction"  
  local_data_file: artifacts/data_ingestion/data          
                   
data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  data_path: artifacts/data_ingestion/data/fraud_test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data/fraud_test.csv
  test_size: 0.2

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json 